---
swagger: "2.0"
info:
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  title: Bank Argent API documentation
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
- http
paths:
  /user/login:
    post:
      tags:
      - User Module
      summary: Login
      description: API for Login
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Login Payload
        required: true
        schema:
          $ref: '#/definitions/Login'
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
      - User Module
      summary: Signup
      description: API for Signup
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Signup Payload
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      tags:
      - User Module
      summary: User Profile API
      description: API for fetching a user profile
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT token
        required: true
        type: string
      security:
      - Bearer: []
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      tags:
      - User Module
      summary: User Profile API
      description: API for updating a user profile
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT token
        required: true
        type: string
      - in: body
        name: body
        description: Update user profile attributes
        required: true
        schema:
          $ref: '#/definitions/UserProfile'
      security:
      - Bearer: []
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile/transactions/:
    get:
      tags:
      - User Transactions
      summary: Transactions for the selected user account
      description: API to fetch user's transactions in one type of account
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT Token
        required: true
        type: string
      responses:
        "200":
          description: User transactions retrieved succesfully
          schema: {}
        "400":
          description: Invalid Fields
        "404":
          description: Not found
        "500":
          description: Internal server error
    post:
      tags:
      - User Transactions
      summary: Create a transaction
      description: Create a transaction
      operationId: postUserTransaction
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Created user object
        required: true
        schema:
          $ref: '#/definitions/Transactions'
      responses:
        "200":
          description: User transaction created succesfully
        "400":
          description: Invalid Fields
        "404":
          description: Not found
        "500":
          description: Internal Server error
  /user/profile/transactions/${transactionID}:
    get:
      tags:
      - User Transactions
      summary: User selected transaction
      description: API to fetch user's selected transaction
      operationId: userTransaction
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT Token
        required: true
        type: string
      - name: transactionID
        in: path
        description: ID of the transaction to get
        required: true
        type: integer
      responses:
        "200":
          description: User transaction retrieved succesfully
          schema:
            $ref: '#/definitions/Transactions'
        "400":
          description: Invalid Fields
        "404":
          description: Not found
        "500":
          description: Internal Server error
    put:
      tags:
      - User Transactions
      summary: Update user selected transaction
      description: API to modify user's selected transaction
      operationId: updateSavings
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT Token
        required: true
        type: string
      - in: body
        name: body
        description: Transaction details that need to be updated
        required: true
        schema:
          $ref: '#/definitions/body'
      - name: transactionID
        in: path
        description: Numeric ID of the transaction to get
        required: true
        type: integer
      responses:
        "200":
          description: Transaction details updated succesfully
          schema:
            $ref: '#/definitions/inline_response_200'
        "400":
          description: Invalid Fields
        "404":
          description: Not found
        "500":
          description: Internal Server error
    delete:
      tags:
      - User Transactions
      summary: Delete user selected transaction
      description: Delete user's selected transaction
      operationId: deleteUserTransaction
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT Token
        required: true
        type: string
      - name: transactionID
        in: path
        description: ID of the transaction to get
        required: true
        type: integer
      responses:
        "200":
          description: User transaction deleted succesfully
        "400":
          description: Invalid Fields
        "404":
          description: Not found
        "500":
          description: Internal Server error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        $ref: '#/definitions/ApiResponse_body'
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transactions:
    type: object
    properties:
      id:
        type: integer
        format: int32
      transaction:
        $ref: '#/definitions/Transactions_transaction'
  body:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string
  inline_response_200:
    type: object
    properties:
      status:
        type: integer
        format: int32
      message:
        type: string
      body:
        $ref: '#/definitions/body'
  ApiResponse_body:
    type: object
    properties:
      id:
        type: string
      email:
        type: string
  Transactions_transaction:
    type: object
    properties:
      date:
        type: string
      description:
        type: string
      amount:
        type: integer
      type:
        type: string
      category:
        type: string
      notes:
        type: string
